
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 25 2025 20:37:46

// Verification Directory fv/synth_wrapper 

module counter(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire n_5, n_10, n_11, n_28, n_47, n_60, n_68, n_69;
  wire n_70, n_71, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_83, n_84, n_91, n_92, n_93, n_100, n_101, n_102;
  sky130_fd_sc_hd__dfrtp_1 \out_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (n_78), .Q (out[3]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (n_75), .Q (out[2]));
  sky130_fd_sc_hd__dfrtp_2 \out_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (n_102), .Q (n_28));
  sky130_fd_sc_hd__nand2_2 g513(.A (sel), .B (n_60), .Y (n_11));
  sky130_fd_sc_hd__dfrtp_2 \out_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (n_5), .Q (out[0]));
  sky130_fd_sc_hd__nand2_1 g515(.A (n_83), .B (n_28), .Y (n_10));
  sky130_fd_sc_hd__buf_4 g520(.A (n_69), .X (n_5));
  sky130_fd_sc_hd__nand3_1 g361(.A (sel), .B (n_28), .C (out[2]), .Y
       (n_47));
  sky130_fd_sc_hd__inv_2 fopt531(.A (n_28), .Y (n_60));
  sky130_fd_sc_hd__nand2_2 g23(.A (n_68), .B (n_70), .Y (n_71));
  sky130_fd_sc_hd__nand2_2 g24(.A (n_60), .B (out[0]), .Y (n_68));
  sky130_fd_sc_hd__nand2_1 g25(.A (n_28), .B (n_69), .Y (n_70));
  sky130_fd_sc_hd__inv_2 g26(.A (out[0]), .Y (n_69));
  sky130_fd_sc_hd__o2bb2ai_1 g46(.A1_N (n_73), .A2_N (n_74), .B1
       (n_73), .B2 (n_74), .Y (n_75));
  sky130_fd_sc_hd__clkbuf_1 g48(.A (n_84), .X (n_73));
  sky130_fd_sc_hd__nor2_2 g47(.A (n_71), .B (n_101), .Y (n_74));
  sky130_fd_sc_hd__xnor2_1 g104(.A (n_76), .B (n_77), .Y (n_78));
  sky130_fd_sc_hd__inv_2 g106(.A (out[3]), .Y (n_76));
  sky130_fd_sc_hd__a21oi_2 g105(.A1 (n_92), .A2 (n_47), .B1 (n_71), .Y
       (n_77));
  sky130_fd_sc_hd__inv_2 g539(.A (sel), .Y (n_83));
  sky130_fd_sc_hd__clkinv_1 g19(.A (out[2]), .Y (n_84));
  sky130_fd_sc_hd__nand3_2 g543(.A (n_91), .B (n_83), .C (n_84), .Y
       (n_92));
  sky130_fd_sc_hd__clkinv_1 g544(.A (n_28), .Y (n_91));
  sky130_fd_sc_hd__inv_1 fopt545(.A (n_93), .Y (out[1]));
  sky130_fd_sc_hd__dlymetal6s2s_1 g1(.A (n_91), .X (n_93));
  sky130_fd_sc_hd__xnor2_1 g548(.A (n_100), .B (n_101), .Y (n_102));
  sky130_fd_sc_hd__inv_2 g549(.A (n_5), .Y (n_100));
  sky130_fd_sc_hd__nand2_2 g550(.A (n_11), .B (n_10), .Y (n_101));
endmodule

module synth_wrapper(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire \out_reg[0]_12 , \out_reg[1]_13 , \out_reg[2]_14 ,
       \out_reg[3]_15 ;
  counter u1(.clk (clk), .rst_n (rst_n), .sel (sel), .out
       ({\out_reg[3]_15 , \out_reg[2]_14 , \out_reg[1]_13 ,
       \out_reg[0]_12 }));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[3]_15 ), .Q (out[3]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[2]_14 ), .Q (out[2]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[0]_12 ), .Q (out[0]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[1]_13 ), .Q (out[1]));
endmodule

