
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 25 2025 20:37:36

// Verification Directory fv/synth_wrapper 

module counter(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19;
  sky130_fd_sc_hd__dfrtp_1 \out_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (n_19), .Q (out[3]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (n_18), .Q (out[2]));
  sky130_fd_sc_hd__xnor2_1 g501(.A (n_3), .B (n_0), .Y (n_19));
  sky130_fd_sc_hd__dfrtp_2 \out_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (n_17), .Q (out[1]));
  sky130_fd_sc_hd__xnor2_1 g503(.A (n_7), .B (n_16), .Y (n_18));
  sky130_fd_sc_hd__xnor2_1 g505(.A (n_6), .B (n_12), .Y (n_17));
  sky130_fd_sc_hd__nor2_2 g506(.A (n_13), .B (n_12), .Y (n_16));
  sky130_fd_sc_hd__nand3_1 g509(.A (out[1]), .B (out[2]), .C (sel), .Y
       (n_15));
  sky130_fd_sc_hd__nand3_2 g510(.A (n_1), .B (n_2), .C (n_7), .Y
       (n_14));
  sky130_fd_sc_hd__nand2_2 g511(.A (n_9), .B (n_8), .Y (n_13));
  sky130_fd_sc_hd__nand2_2 g512(.A (n_11), .B (n_10), .Y (n_12));
  sky130_fd_sc_hd__nand2_2 g513(.A (sel), .B (n_1), .Y (n_11));
  sky130_fd_sc_hd__dfrtp_2 \out_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (n_5), .Q (out[0]));
  sky130_fd_sc_hd__nand2_1 g515(.A (out[1]), .B (n_2), .Y (n_10));
  sky130_fd_sc_hd__nand2_2 g516(.A (n_1), .B (out[0]), .Y (n_9));
  sky130_fd_sc_hd__nand2_1 g517(.A (out[1]), .B (n_4), .Y (n_8));
  sky130_fd_sc_hd__inv_2 g518(.A (out[2]), .Y (n_7));
  sky130_fd_sc_hd__inv_1 g519(.A (n_5), .Y (n_6));
  sky130_fd_sc_hd__buf_2 g520(.A (n_4), .X (n_5));
  sky130_fd_sc_hd__inv_1 g521(.A (out[0]), .Y (n_4));
  sky130_fd_sc_hd__inv_1 g522(.A (out[3]), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g523(.A (sel), .Y (n_2));
  sky130_fd_sc_hd__inv_4 g524(.A (out[1]), .Y (n_1));
  sky130_fd_sc_hd__a21oi_2 g2(.A1 (n_14), .A2 (n_15), .B1 (n_13), .Y
       (n_0));
endmodule

module synth_wrapper(clk, rst_n, sel, out);
  input clk, rst_n, sel;
  output [3:0] out;
  wire clk, rst_n, sel;
  wire [3:0] out;
  wire \out_reg[0]_12 , \out_reg[1]_13 , \out_reg[2]_14 ,
       \out_reg[3]_15 ;
  counter u1(.clk (clk), .rst_n (rst_n), .sel (sel), .out
       ({\out_reg[3]_15 , \out_reg[2]_14 , \out_reg[1]_13 ,
       \out_reg[0]_12 }));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[3] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[3]_15 ), .Q (out[3]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[2] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[2]_14 ), .Q (out[2]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[0] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[0]_12 ), .Q (out[0]));
  sky130_fd_sc_hd__dfrtp_1 \out_reg[1] (.RESET_B (rst_n), .CLK (clk),
       .D (\out_reg[1]_13 ), .Q (out[1]));
endmodule

